extends:
  - "@commitlint/config-conventional"
rules:
  header-max-length:
    - 2
    - always
    - 140
  subject-case:
    - 0
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - style
      - test
      - chore
